"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import math
import os
from pathlib import Path
from urllib.parse import urlparse

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t9i%%mv)rw^om#mz=^lo+b3tgri8@fb+yakk1@3%x8f$c&6-hm'

# Gemini configuration. Keep the actual key in .env, never in source control.
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')
GEMINI_EMBEDDING_MODEL = os.getenv(
    'GEMINI_EMBEDDING_MODEL',
    'gemini-embedding-001',
)
GEMINI_CHAT_MODEL = os.getenv(
    'GEMINI_CHAT_MODEL',
    'gemini-3.5-flash-lite',
)


def get_http_url_setting(name: str, default: str) -> str:
    """Read and validate an HTTP(S) service base URL."""
    value = os.getenv(name, default).strip().rstrip('/')
    parsed = urlparse(value)
    if (
        parsed.scheme not in {'http', 'https'}
        or not parsed.netloc
        or parsed.query
        or parsed.fragment
    ):
        raise ImproperlyConfigured(
            f'{name} must be an HTTP(S) base URL without a query or fragment.'
        )
    return value


def get_positive_float_setting(name: str, default: float) -> float:
    """Read a finite, positive floating-point setting."""
    raw_value = os.getenv(name, str(default))
    try:
        value = float(raw_value)
    except ValueError as error:
        raise ImproperlyConfigured(f'{name} must be a number.') from error

    if not math.isfinite(value) or value <= 0:
        raise ImproperlyConfigured(f'{name} must be greater than zero.')
    return value


def get_positive_int_setting(name: str, default: int) -> int:
    """Read a positive integer setting."""
    raw_value = os.getenv(name, str(default))
    try:
        value = int(raw_value)
    except ValueError as error:
        raise ImproperlyConfigured(f'{name} must be an integer.') from error

    if value <= 0:
        raise ImproperlyConfigured(f'{name} must be greater than zero.')
    return value


# ASP.NET typed Mapbox tool service and orchestration limits.
MAPBOX_TOOL_BASE_URL = get_http_url_setting(
    'MAPBOX_TOOL_BASE_URL',
    'http://localhost:5257',
)
MAPBOX_TOOL_TIMEOUT_SECONDS = get_positive_float_setting(
    'MAPBOX_TOOL_TIMEOUT_SECONDS',
    12,
)
CHATBOT_MAX_TOOL_CALLS = get_positive_int_setting(
    'CHATBOT_MAX_TOOL_CALLS',
    4,
)

# RAG pipeline configuration.
KNOWLEDGE_BASE_DIR = BASE_DIR / 'chatbot' / 'knowledge_base'
CHROMA_DB_DIR = BASE_DIR / 'chroma_db'
CHROMA_COLLECTION_NAME = 'travel_knowledge'
RAG_CHUNK_SIZE = 2000
RAG_CHUNK_OVERLAP = 200
RAG_RETRIEVAL_TOP_K = 5
RAG_RELEVANCE_THRESHOLD = 0.5

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'chatbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
