@backend_HostAddress = http://localhost:5257
@query = Eiffel Tower

GET {{backend_HostAddress}}/api/mapbox/search?q={{query}}&language=en&limit=5&types=poi&proximity=2.2945,48.8584
Accept: application/geo+json

###

GET {{backend_HostAddress}}/api/mapbox/categories?language=en
Accept: application/json

###

GET {{backend_HostAddress}}/api/mapbox/categories/restaurant?language=en&limit=10&proximity=2.2945,48.8584
Accept: application/geo+json

###

GET {{backend_HostAddress}}/api/mapbox/reverse?longitude=2.2945&latitude=48.8584&language=en&limit=5
Accept: application/geo+json

###
